FROM ubuntu:bionic

MAINTAINER Igor Rabkin <igor.rabkin@xiaoyi.com>

RUN apt-get update && yes | apt-get upgrade && \
    mkdir -p /tensorflow/models

RUN apt-get install -y git python-pip && \
    PYTHONWARNINGS=ignore:DEPRECATION pip install --upgrade pip

RUN PYTHONWARNINGS=ignore:DEPRECATION pip --no-cache-dir install --upgrade tensorflow==1.12.0

RUN apt-get install -y \
    protobuf-compiler \
    python-pil \
    python-lxml && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN PYTHONWARNINGS=ignore:DEPRECATION pip install jupyter matplotlib

RUN git clone --progress https://github.com/tensorflow/models.git /tensorflow/models

WORKDIR /tensorflow/models/research

RUN protoc object_detection/protos/*.proto --python_out=. && \
    export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim && \
    jupyter notebook --generate-config --allow-root && \
    echo "c.NotebookApp.password = u'sha1:6a3f528eec40:6e896b6e4828f525a6e20e5411cd1c8075d68619'" >> /root/.jupyter/jupyter_notebook_config.py

EXPOSE 8889

CMD ["jupyter", "notebook", "--allow-root", "--notebook-dir=/tensorflow/models/research/object_detection", "--ip=0.0.0.0", "--port=8888", "--no-browser"]
